// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEvb1wiR8DXQAfkwbQo_ERk-SP0sj1-ag',
    appId: '1:1088741098589:web:4f5272cb63ab4d9fdeb9b4',
    messagingSenderId: '1088741098589',
    projectId: 'it302todolistapp-fe622',
    authDomain: 'it302todolistapp-fe622.firebaseapp.com',
    storageBucket: 'it302todolistapp-fe622.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiQV80Hiae8AtdC0GNzBSUs7kONxKhQSc',
    appId: '1:1088741098589:android:5f53bdd10eccd1dedeb9b4',
    messagingSenderId: '1088741098589',
    projectId: 'it302todolistapp-fe622',
    storageBucket: 'it302todolistapp-fe622.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu8-ZYlqPL5ryxm4zpDsC1OZnc6QQSENk',
    appId: '1:1088741098589:ios:1aa75dfd6fa91bacdeb9b4',
    messagingSenderId: '1088741098589',
    projectId: 'it302todolistapp-fe622',
    storageBucket: 'it302todolistapp-fe622.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

}